### ISSUE TITLE
I find that there seems to be some strange things in the evaluation of model.

### ISSUE THREAD

**Issue by leexinhao** [OpenGVLab/VideoMAEv2#23]
I did some simple finetuning training and it seems that some of it looks normal :
![A1RSV8H}1XR1PN4~0`K@NFF](https://github.com/OpenGVLab/VideoMAEv2/assets/48858574/032a7055-673a-4aff-b1d1-a507ab6ca906)

But when I retested the saved pt file with the '--eval' parameter, I got slightly different results: in particular, the results of the single view test were quite different (65.xx vs. 67.xx):
![image](https://github.com/OpenGVLab/VideoMAEv2/assets/48858574/18118859-c2e5-4a1d-ab66-e1a04f8362d6)

Is this normal or a bug? Is there something wrong with my understanding?

**Comment by congee524** [comment]
The inconsistent results when reloading ckpt are due to the **run-time parameter**, such as `running_mean` & `running_var` in normalization layers.

During training, each model on every GPU has its own run-time parameters. However, we only save the checkpoint on GPU0. When reloading the model, the run-time parameters of the model on other GPUs are loaded from the model on GPU0, leading to slight differences in the results.

**Comment by leexinhao** [comment]
I don't find that in your code. Can you show me the location of the corresponding implementation?

**Comment by congee524** [comment]
https://github.com/OpenGVLab/VideoMAEv2/blob/9492db0047a9e30446a4093543a1a39dfe62b459/run_class_finetuning.py#L439-L442

This code is modified from DeiT, and I haven't looked closely at how it's handled, but it should be related to the sampler.

**Comment by leexinhao** [comment]
I see, thank you!
